#!/bin/bash

# Change to original directory at the end
trap "cd $PWD" EXIT

# Change to script directory
function cd_root_dir
{
    local source="${BASH_SOURCE[0]}"
    while [[ -L ${source} ]]; do
        # shellcheck disable=SC1117
        source=$(find "${source}" -type l -ls | sed -n 's/^.* -> \(.*\)/\1/p')
    done
    local dir=$(cd -P "$(dirname "${source}")" && pwd)
    cd $dir || exit 1
}
cd_root_dir

source functions || die "Failed to source functions."

tmpdir=$(dirname $(mktemp -u))

assert_cmd_exist stow
setup_build_dir

while IFS= read -r line; do
    manifest_download "$tmpdir" $line
done <MANIFEST && echo "--"

cd build
find . -type f -name ".DS_Store" -delete

sed -e "s/{OS}/$(uname)/" -i .bak home/dot-sys.in
/bin/mv home/dot-sys.in home/dot-sys
/bin/rm home/dot-sys.in.bak

stow -v --dotfiles --target $HOME -D home && echo "--" || die "Stow failed."
stow -v --dotfiles --target $HOME home && echo "--" || die "Stow failed."
