#!/bin/bash

# Change dir to the original one at the exit
trap "cd $PWD" EXIT

# Change dir to script's
{
    src="${BASH_SOURCE[0]}"
    while [[ -L ${src} ]]; do
        # shellcheck disable=SC1117
        src=$(find "${src}" -type l -ls | sed -n 's/^.* -> \(.*\)/\1/p')
    done
    dir=$(cd -P "$(dirname "${src}")" && pwd)
    cd $dir || exit 1
}

source functions || die "Failed to source functions."

lock

assert_cmd_exist "stow"
setup_build_dir

# Download files
{
    while IFS= read -r line; do
        manifest_download $line
    done <MANIFEST && echo "--"
}

find build/ -type f -name ".DS_Store" -delete

# .sys.in setup
{
    sys_set OS $(uname)

    cmd_exist "trash" && sys_set "TRASH_CMD" "trash" ||
        cmd_exist "rmtrash" && sys_set "TRASH_CMD" "rmtrash" ||
        sys_set "TRASH_CMD" ""

    cmd_exist fzf && sys_set HAS_FZF 1 || sys_set HAS_FZF 0
    cmd_exist mcfly && sys_set HAS_MCFLY 1 || sys_set HAS_MCFLY 0
    cmd_exist brew && sys_set BREW_PREFIX $(brew --prefix)
    cmd_exist brew && sys_set HAS_BREW 1 || sys_set HAS_BREW 0
    cmd_exist cargo && sys_set HAS_CARGO 1 || sys_set HAS_CARGO 0
    cmd_exist kitty && sys_set HAS_KITTY 1 || sys_set HAS_KITTY 0

    /bin/mv build/home/.sys.in build/home/.sys
    /bin/rm build/home/.sys.in.bak
}

# Git setup
{
    if ! git config --global --get user.email >/dev/null; then
        git config --global user.email "danilo.horta@pm.me"
        git config --global user.name "Danilo Horta"
    fi
    if ! git config --global credential.helper >/dev/null; then
        git config --global credential.helper manager-core
    fi
}

# Key repeat setup
{
    defaults write -g InitialKeyRepeat -int 10
    defaults write -g KeyRepeat -int 1
}

(
    cd build
    stow -v --target $HOME -D home && echo "--" || die "Stow failed."
    stow -v --target $HOME home && echo "--" || die "Stow failed."
)

unlock
