#!/bin/bash

alias b="git branch -a"
alias e="exit"
alias g="git"
alias icat="kitty +kitten icat"
if [ "$OS" = "Darwin" ]; then
    alias l="ls"
    alias ll="ls -lah"
else
    alias l="ls --color=auto"
    alias ll="ls -lah --color=auto"
fi
alias t=tree
alias s="git status"
alias vim="$EDITOR"
alias v="$EDITOR"
alias ver="version"
alias ..="cd .."
# https://apple.stackexchange.com/questions/17622/how-can-i-make-rm-move-files-to-the-trash-can
alias rm="echo Use 'del', or the full path i.e. '/bin/rm'"
alias del="trash"
alias vw="vim-which"
